#!/usr/bin/env bash
# Per-boot startup for the ApplyWizz Signal Cloud Agent environment.
# Brings up Docker + the local Supabase stack, writes apps/web/.env.local, and
# seeds local test users. Idempotent and safe to re-run; it returns once the
# stack is ready (the web dev server itself runs as a terminal).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
# shellcheck source=./lib.sh
source "$REPO_ROOT/.cursor/lib.sh"

ensure_docker
fix_docker_forwarding

echo "==> Starting local Supabase stack"
if supabase status >/dev/null 2>&1; then
  echo "   Supabase already running"
else
  supabase start --exclude "$SUPABASE_EXCLUDE"
fi

ENV_FILE="$REPO_ROOT/apps/web/.env.local"
if [ ! -f "$ENV_FILE" ]; then
  echo "==> Writing apps/web/.env.local from local Supabase credentials"
  status_env="$(supabase status -o env)"
  get() { printf '%s\n' "$status_env" | grep "^$1=" | cut -d= -f2- | tr -d '"'; }
  cat > "$ENV_FILE" <<EOF
# Auto-generated by .cursor/start.sh for local development.
# Points at the local Supabase stack; values are Supabase's well-known local
# demo keys (not real secrets). Add provider secrets (Microsoft/OpenAI/etc.)
# below as needed — this file is gitignored and preserved across boots.
NEXT_PUBLIC_SUPABASE_URL=$(get API_URL)
NEXT_PUBLIC_SUPABASE_ANON_KEY=$(get ANON_KEY)
SUPABASE_SERVICE_ROLE_KEY=$(get SERVICE_ROLE_KEY)
APP_BASE_URL=http://127.0.0.1:3000
WEBHOOK_BASE_URL=http://127.0.0.1:3000
ENCRYPTION_KEY=local-dev-encryption-key-not-a-real-secret
INTERNAL_QUEUE_SECRET=local-dev-internal-queue-secret
LOG_LEVEL=info
EOF
else
  echo "==> apps/web/.env.local already present — leaving it untouched"
fi

echo "==> Seeding local test users (idempotent)"
pnpm run seed:users || echo "   (seed skipped — Supabase auth not reachable)"

echo "==> Environment ready. Test accounts use password: LocalDevPassword123!"
